// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RateFilms.Infrastructure.Data;

#nullable disable

namespace RateFilms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231121224630_4.1")]
    partial class _41
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.ActorDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FilmId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("ImageId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.FilmDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AgeRating")
                        .HasColumnType("real");

                    b.Property<string>("Autor")
                        .HasColumnType("text");

                    b.Property<float?>("AvgRating")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.ImageDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FilmId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.SeasonDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("AvgRating")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RealeseDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SerialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SerialId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.SerialDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<float>("AvgRating")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeriesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.UserDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.ActorDbModel", b =>
                {
                    b.HasOne("RateFilms.Infrastructure.StorageModels.FilmDbModel", "Film")
                        .WithMany("Actors")
                        .HasForeignKey("FilmId");

                    b.HasOne("RateFilms.Infrastructure.StorageModels.ImageDbModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("RateFilms.Infrastructure.StorageModels.SeasonDbModel", "Season")
                        .WithMany("Actors")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Film");

                    b.Navigation("Image");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.ImageDbModel", b =>
                {
                    b.HasOne("RateFilms.Infrastructure.StorageModels.FilmDbModel", "Film")
                        .WithMany("Images")
                        .HasForeignKey("FilmId");

                    b.HasOne("RateFilms.Infrastructure.StorageModels.SeasonDbModel", "Season")
                        .WithMany("Images")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Film");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.SeasonDbModel", b =>
                {
                    b.HasOne("RateFilms.Infrastructure.StorageModels.SerialDbModel", "Serial")
                        .WithMany("Seasons")
                        .HasForeignKey("SerialId");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.FilmDbModel", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.SeasonDbModel", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("RateFilms.Infrastructure.StorageModels.SerialDbModel", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
