// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RateFilms.Infrastructure.Data;

#nullable disable

namespace RateFilms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240715165507_20.3")]
    partial class _203
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreDbModelMovieDbModel", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MoviesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenreId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("PersonInMovieDbModelProfessionDbModel", b =>
                {
                    b.Property<int>("ProfessionsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonInMoviesMovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonInMoviesPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfessionsId", "PersonInMoviesMovieId", "PersonInMoviesPersonId");

                    b.HasIndex("PersonInMoviesMovieId", "PersonInMoviesPersonId");

                    b.ToTable("PersonInMovieProfession", (string)null);
                });

            modelBuilder.Entity("RateFilms.Common.Models.Localization.Culture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Culture");
                });

            modelBuilder.Entity("RateFilms.Common.Models.Localization.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CultureId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CultureId");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.AdminNoteDbModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "ReviewId");

                    b.HasIndex("ReviewId")
                        .IsUnique();

                    b.ToTable("NoteToReview");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.CommentDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FavoriteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.CommentUserDbModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.FavoriteMovieDbModel", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteMovie");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.GenreDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Genre")
                        .IsUnique();

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.ImageDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FilmId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Img")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isPreview")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.MovieDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MovieDbModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.PersonDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.PersonInMovieDbModel", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("MovieId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInMovie");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.ProfessionDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Profession")
                        .IsUnique();

                    b.ToTable("Profession");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SeasonDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CountMaxSeries")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RealeseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SerialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SerialId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SeriesDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviewImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RealeseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PreviewImageId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.TokenDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateOfEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.UserDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ImageId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.FilmDbModel", b =>
                {
                    b.HasBaseType("RateFilms.Domain.Models.StorageModels.MovieDbModel");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("FilmDbModel");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SerialDbModel", b =>
                {
                    b.HasBaseType("RateFilms.Domain.Models.StorageModels.MovieDbModel");

                    b.Property<Guid?>("PreviewImageId")
                        .HasColumnType("uuid");

                    b.HasIndex("PreviewImageId");

                    b.HasDiscriminator().HasValue("SerialDbModel");
                });

            modelBuilder.Entity("GenreDbModelMovieDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.GenreDbModel", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.MovieDbModel", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonInMovieDbModelProfessionDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.ProfessionDbModel", null)
                        .WithMany()
                        .HasForeignKey("ProfessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.PersonInMovieDbModel", null)
                        .WithMany()
                        .HasForeignKey("PersonInMoviesMovieId", "PersonInMoviesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RateFilms.Common.Models.Localization.Resource", b =>
                {
                    b.HasOne("RateFilms.Common.Models.Localization.Culture", "Culture")
                        .WithMany("Resources")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Culture");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.AdminNoteDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.CommentDbModel", "Review")
                        .WithOne("AdminNote")
                        .HasForeignKey("RateFilms.Domain.Models.StorageModels.AdminNoteDbModel", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.UserDbModel", "User")
                        .WithMany("AdminNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.CommentDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.FavoriteMovieDbModel", "Favorite")
                        .WithMany("Comments")
                        .HasForeignKey("FavoriteId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.CommentUserDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.CommentDbModel", "Comment")
                        .WithMany("Users")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.UserDbModel", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.FavoriteMovieDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.MovieDbModel", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.UserDbModel", "User")
                        .WithMany("FavoriteMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.ImageDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.FilmDbModel", "Film")
                        .WithMany("Images")
                        .HasForeignKey("FilmId");

                    b.HasOne("RateFilms.Domain.Models.StorageModels.SeasonDbModel", "Season")
                        .WithMany("Images")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Film");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.PersonDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.ImageDbModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.PersonInMovieDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.MovieDbModel", "Movie")
                        .WithMany("People")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateFilms.Domain.Models.StorageModels.PersonDbModel", "Person")
                        .WithMany("Movies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SeasonDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.SerialDbModel", "Serial")
                        .WithMany("Seasons")
                        .HasForeignKey("SerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SeriesDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.ImageDbModel", "PreviewImage")
                        .WithMany()
                        .HasForeignKey("PreviewImageId");

                    b.HasOne("RateFilms.Domain.Models.StorageModels.SeasonDbModel", "Season")
                        .WithMany("Series")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreviewImage");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.UserDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.ImageDbModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SerialDbModel", b =>
                {
                    b.HasOne("RateFilms.Domain.Models.StorageModels.ImageDbModel", "PreviewImage")
                        .WithMany()
                        .HasForeignKey("PreviewImageId");

                    b.Navigation("PreviewImage");
                });

            modelBuilder.Entity("RateFilms.Common.Models.Localization.Culture", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.CommentDbModel", b =>
                {
                    b.Navigation("AdminNote");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.FavoriteMovieDbModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.MovieDbModel", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("People");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.PersonDbModel", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SeasonDbModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.UserDbModel", b =>
                {
                    b.Navigation("AdminNotes");

                    b.Navigation("Comments");

                    b.Navigation("FavoriteMovies");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.FilmDbModel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("RateFilms.Domain.Models.StorageModels.SerialDbModel", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
