namespace RateFilms.Domain.Models.DomainModels
{
    public enum Genre
    {
        None,
        Action,
        Fantasy,
        Horror,
        Adventure,
        Animated,
        Comedy,
        Drama,
        Thriller,
        Historical,
        Romance,
        Crime,
        Anime,
        Biography,
        Western,
        Military,
        Detective,
        Children,
        Documentary,
        Game,
        Concert,
        ShortFilm,
        Music,
        Musical,
        News,
        Family,
        Sports,
        Fantastic,
        Ceremony
    }
}
